In [1]:
import pandas as pd
import matplotlib as plt
import numpy as np
import datetime as dt

In [2]:
state_turnover_perc_change = pd.read_excel("850104.xlsx", sheet_name="Data1")
industry_turnover_perc_change = pd.read_excel("850102.xlsx", sheet_name="Data1")

state_turnover_perc_change

,Unnamed: 0,% change from preceding month ; New South Wales ; Total (Industry) ;,% change from preceding month ; Victoria ; Total (Industry) ;,% change from preceding month ; Queensland ; Total (Industry) ;,% change from preceding month ; South Australia ; Total (Industry) ;,% change from preceding month ; Western Australia ; Total (Industry) ;,% change from preceding month ; Tasmania ; Total (Industry) ;,% change from preceding month ; Northern Territory ; Total (Industry) ;,% change from preceding month ; Australian Capital Territory ; Total (Industry) ;,% change from preceding month ; Total (State) ; Total (Industry) ;,...,% change from preceding month ; Total (State) ; Total (Industry) ;.1,% change from preceding month ; New South Wales ; Total (Industry) ;.2,% change from preceding month ; Victoria ; Total (Industry) ;.2,% change from preceding month ; Queensland ; Total (Industry) ;.2,% change from preceding month ; South Australia ; Total (Industry) ;.2,% change from preceding month ; Western Australia ; Total (Industry) ;.2,% change from preceding month ; Tasmania ; Total (Industry) ;.2,% change from preceding month ; Northern Territory ; Total (Industry) ;.2,% change from preceding month ; Australian Capital Territory ; Total (Industry) ;.2,% change from preceding month ; Total (State) ; Total (Industry) ;.2
0,Unit,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,...,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent
1,Series Type,Original,Original,Original,Original,Original,Original,Original,Original,Original,...,Seasonally Adjusted,Trend,Trend,Trend,Trend,Trend,Trend,Trend,Trend,Trend
2,Data Type,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,...,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,2021-08-01 00:00:00,-4,-3.5,-2.5,4.8,0.7,-3,-4,-20.7,-2.7,...,-1.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,2021-09-01 00:00:00,3.9,-1.4,4.4,1.2,1.9,1.3,-4,-12.4,1.9,...,1.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,2021-10-01 00:00:00,18.2,8,4.1,4.5,5.8,4.4,2.4,29.3,9.8,...,4.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,2021-11-01 00:00:00,9.5,24.8,3.2,5.2,4,6.6,-4.9,23.3,10.9,...,7.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,2021-12-01 00:00:00,15.8,13.3,19.6,15.9,18,17.9,14.2,14.1,16.1,...,-4.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
industry_turnover_perc_change

,Unnamed: 0,% change from preceding month ; Total (State) ; Food retailing ;,% change from preceding month ; Total (State) ; Household goods retailing ;,"% change from preceding month ; Total (State) ; Clothing, footwear and personal accessory retailing ;",% change from preceding month ; Total (State) ; Department stores ;,% change from preceding month ; Total (State) ; Other retailing ;,"% change from preceding month ; Total (State) ; Cafes, restaurants and takeaway food services ;",% change from preceding month ; Total (State) ; Total (Industry) ;,% change from preceding month ; Total (State) ; Food retailing ;.1,% change from preceding month ; Total (State) ; Household goods retailing ;.1,...,% change from preceding month ; Total (State) ; Other retailing ;.1,"% change from preceding month ; Total (State) ; Cafes, restaurants and takeaway food services ;.1",% change from preceding month ; Total (State) ; Total (Industry) ;.1,% change from preceding month ; Total (State) ; Food retailing ;.2,% change from preceding month ; Total (State) ; Household goods retailing ;.2,"% change from preceding month ; Total (State) ; Clothing, footwear and personal accessory retailing ;.2",% change from preceding month ; Total (State) ; Department stores ;.2,% change from preceding month ; Total (State) ; Other retailing ;.2,"% change from preceding month ; Total (State) ; Cafes, restaurants and takeaway food services ;.2",% change from preceding month ; Total (State) ; Total (Industry) ;.2
0,Unit,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,...,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent
1,Series Type,Original,Original,Original,Original,Original,Original,Original,Seasonally Adjusted,Seasonally Adjusted,...,Seasonally Adjusted,Seasonally Adjusted,Seasonally Adjusted,Trend,Trend,Trend,Trend,Trend,Trend,Trend
2,Data Type,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,...,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481,2021-08-01 00:00:00,1.5,-2.7,-20.1,-21.4,0.8,-6.6,-2.7,2.1,-2.3,...,0.8,-7,-1.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,2021-09-01 00:00:00,-1.8,5.4,9.8,10.2,1.9,4.7,1.9,-1.4,4.3,...,2.1,5,1.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
483,2021-10-01 00:00:00,4,10.8,34.5,31.3,6,16.2,9.8,-0.5,4.5,...,2.2,12.3,4.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
484,2021-11-01 00:00:00,-4,18.8,49.1,41,18.2,7.8,10.9,-2.5,11.6,...,7.3,9.3,7.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
485,2021-12-01 00:00:00,19.8,6,27.6,31.3,14,8.5,16.1,2.2,-9.2,...,-4,-0.7,-4.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
covid_cases_df = pd.read_csv ('cases_daily_state.csv')
#convert Date to datetime format
covid_cases_df["Date"] = pd.to_datetime(covid_cases_df["Date"])
covid_cases_df.head()

        Date  NSW  VIC  QLD   SA   WA  TAS   NT  ACT
0 2020-01-25    3    1  0.0  0.0  0.0    0  0.0  0.0
1 2020-01-26    0    0  0.0  0.0  0.0    0  0.0  0.0
2 2020-01-27    1    0  0.0  0.0  0.0    0  0.0  0.0
3 2020-01-28    0    0  0.0  0.0  0.0    0  0.0  0.0
4 2020-01-29    0    2  2.0  0.0  0.0    0  0.0  0.0

In [5]:
covid_cases_df.set_index('Date', inplace=True)
covid_cases_df.index = pd.to_datetime(covid_cases_df.index)
monthly_cases_df = covid_cases_df.resample('1M').sum()
monthly_cases_df.head()

             NSW   VIC    QLD     SA     WA  TAS    NT   ACT
Date
2020-01-31   222   619   46.0   31.0   34.0    2   2.0   5.0
2020-02-29   185   933   71.0   25.0   14.0    3   6.0   4.0
2020-03-31  2094  1577  764.0  340.0  379.0   74  29.0  83.0
2020-04-30   328   797  103.0   26.0   51.0   79   0.0   7.0
2020-05-31   184  1079   30.0   11.0   68.0    7   2.0   3.0